import fs from "fs"; import path from "path"; import { fileURLToPath } from "url";
import { Config } from "../vendor/openfront/src/core/configuration/Config";
import { Executor } from "../vendor/openfront/src/core/execution/ExecutionManager";
import { Game, PlayerInfo, PlayerType } from "../vendor/openfront/src/core/game/Game";
import { createGame } from "../vendor/openfront/src/core/game/GameImpl";
import { createNationsForGame } from "../vendor/openfront/src/core/game/NationCreation";
import { loadTerrainMap } from "../vendor/openfront/src/core/game/TerrainMapLoader";
import { GameRunner } from "../vendor/openfront/src/core/GameRunner";
import { PseudoRandom } from "../vendor/openfront/src/core/PseudoRandom";
import { GameRecord, GameRecordSchema, GameStartInfo } from "../vendor/openfront/src/core/Schemas";
import { decompressGameRecord, simpleHash, toWireGameStartInfo } from "../vendor/openfront/src/core/Util";
import { NodeGameMapLoader } from "../vendor/openfront/tests/perf/fullgame/NodeGameMapLoader";
import { ObsEncoder, NUM_CHANNELS, CHANNELS } from "./obs";
const ENGINE = path.join(path.dirname(fileURLToPath(import.meta.url)), "../vendor/openfront");
async function main(){
  const file=process.argv[2], until=Number(process.argv[3]||3000); console.debug=()=>{};
  const raw=JSON.parse(fs.readFileSync(file,"utf8")); const pp=GameRecordSchema.safeParse(raw);
  const rec:GameRecord=decompressGameRecord(pp.success?pp.data:(raw as GameRecord)); const info=rec.info;
  const gs:GameStartInfo=toWireGameStartInfo({gameID:info.gameID,lobbyCreatedAt:info.lobbyCreatedAt,config:info.config,players:info.players,tribes:info.tribes});
  const cfg=new Config(info.config,null,false);
  const terrain=await loadTerrainMap(info.config.gameMap,info.config.gameMapSize,new NodeGameMapLoader(path.join(ENGINE,"resources/maps")),false);
  const rnd=new PseudoRandom(simpleHash(gs.gameID));
  const humans=gs.players.map(x=>new PlayerInfo(x.username,PlayerType.Human,x.clientID,rnd.nextID(),x.isLobbyCreator??false,x.clanTag,x.friends??[],x.teamIndex??null));
  const nations=createNationsForGame(gs,terrain.nations,terrain.additionalNations,humans.length,rnd);
  const game:Game=createGame(humans,nations,terrain.gameMap,terrain.miniGameMap,cfg,terrain.teamGameSpawnAreas);
  let fatal:string|undefined; const runner=new GameRunner(game,new Executor(game,gs.gameID,undefined,gs.tribes?.map(t=>t.name)),(gu)=>{if("errMsg" in gu)fatal=gu.errMsg;}); runner.init();
  const enc=new ObsEncoder(180,90); enc.initTerrain(game);
  for(const t of rec.turns){ runner.addTurn(t); runner.executeNextTick(); if(fatal){console.error(fatal);process.exit(1);} if(game.ticks()>=until)break; }
  enc.scanTick(game);
  const pl=game.players().filter(x=>x.isAlive()&&x.type()===PlayerType.Human).sort((a,b)=>b.numTilesOwned()-a.numTilesOwned())[0];
  const out=new Float32Array(NUM_CHANNELS*180*90);
  enc.encodeMap(pl,new Set(pl.allies().map(a=>a.smallID())),out);
  const n=180*90;
  console.log("Kanäle:",NUM_CHANNELS,"(soll 18)");
  const nz=(c:number)=>{let k=0,mn=9,mx=-9;for(let i=0;i<n;i++){const v=out[c*n+i];if(v!==0){k++;if(v<mn)mn=v;if(v>mx)mx=v;}}return `${k} nz [${mn.toFixed(2)},${mx.toFixed(2)}]`;};
  const ci=CHANNELS.indexOf("sam_cover"), city=CHANNELS.indexOf("bau_City" as any);
  console.log("Tick",game.ticks());
  console.log("  bau_City:", nz(city), "(Level-skaliert, Betrag 0.4..1.0)");
  console.log("  sam_cover:", nz(ci));
}
main();
